apiVersion: v1
kind: Secret
metadata:
  name: gnlist
  namespace: gn
type: Opaque
data:
  # user: gnuser
  db.user: Z251c2Vy
  # password: gnpassword
  db.user.password: Z25wYXNzd29yZA==
  # password: gnpassword
  root.password: Z25wYXNzd29yZA==
  session.secret: c2vzc2lvbnnly3jldA==
